### ISSUE TITLE
Calculator always stays on screen

### ISSUE THREAD

**Issue by Techial** [Rusketh/FML_Calculator#1]
The new update makes the calculator always stick on the screen.
Would it be possible to hide it again like in 0.0.1?

Thanks.

**Comment by Rusketh** [comment]
Please advise of your selected screen resolution as well as if you use full screen or windowed. If you are in full screen does it show in windowed mode and vice versa.

I am trying to obtain enough data to figure out what causes this issue, since I am unable to reproduce.

**Comment by Techial** [comment]
Well, 1920x1080 monitor, but the game set my resolution to 1600x900 without me noticing.
Forgot to post an update here that switching to 1920x1080 fixed it, but I guess it's still an issue.

**Comment by Rusketh** [comment]
Ok, in an attempt to combat this in 0.0.4 the animation will include a fade out/in effect.

**Comment by Rusketh** [comment]
Should now be fixed, reopen is issue persists after 0.0.3
