### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by FUrusketh** [Rusketh/FML_Calculator#10]
How the hell do you justify going from a calculator to a mess of **unworking** features? just had to wait ten minutes for an autosave because this **crapulator** froze up my keyboard and mouse, making no input do **ANYTHING**. this isn't a matter of just a mod malfunctioning, this is just terribly thought out and executed. **NO MOD SHOULD EVER FORCE ME TO ALT+F4**

**Comment by Rusketh** [comment]
P.S Read the instructions.
