### ISSUE TITLE
Option to rebind F12 to something else

### ISSUE THREAD

**Issue by Ackros** [Rusketh/FML_Calculator#2]
Hi

Looking to see if there is a way to rebind the action key as F12 is universally considered for other tasks like screenshot.

thank you kindly

**Comment by Rusketh** [comment]
Sadly the ability to rebind, isn't going to be an easy task. Maybe in future a future release.

**Comment by isochronous** [comment]
Could you please change the keybind then, please? As soon as Satisfactory releases on Steam, that's gonna take a screenshot every time you toggle the calculator. Maybe something like CTRL-C? Should be a natural keypress for a lot of people...

**Comment by Ackros** [comment]
Yeah that's going to need to be changed to a 2 key press combo, can't be
left as F12 hardcoded.

A more appropriate combo would be Ctrl+NumLock

**Comment by Rusketh** [comment]
Will be fixed in next build hopefully.
You can change the key bind per play session in the new build now though.
Be a while before I am ready to release how ever, lot of changes happening.
