### ISSUE TITLE
Always equals 0

### ISSUE THREAD

**Issue by Dakonin** [Rusketh/FML_Calculator#5]
So for what ever reason every time i try a calculation say 15*6 its 0
either clicking the buttons or using my num pad, its defaulting to 0, Cleared Mem and evrything still just given me the o's

**Comment by ClockwiseGear** [comment]
+1 confirm. I tried several different multiplication and division operations, and all of them resulted in 0 despite the fact I *know* that 120/30 is very much not 0. Also of note is that any operation I tried with a non-whole number also resulted in 0.

**Comment by Vassi** [comment]
This is a feature! https://github.com/Rusketh/FML_Calculator/issues/4

**Comment by ClockwiseGear** [comment]
Looking at the linked issue, I was not using the calculator in that fashion. I still got a result of 0 after clearing the input and entering a new equation.

**Comment by Entar11262** [comment]
Probably related, for some reason, 120+60=0. Occasionally 1+1=0 as well. Clearing sometimes fixes it, until i try and do 120+60 again, then everything equals 0.

**Comment by Dakonin** [comment]
sometimes it would work. 80% of the time it would be 0. it was never the same thing that got it back working. seemed pretty random

**Comment by Megalingo** [comment]
After the first operation, the result is always 0, the only way to "restart it" is by clicking CA.
