### ISSUE TITLE
Top Window?

### ISSUE THREAD

**Issue by PowerPotassium** [Rusketh/FML_Calculator#6]
Like, can it be made so that you can press F9 to bring up the calculator even if you're already in a UI, putting the calculator in front of the previous one. I like to be able to see the numbers in the other UI while doing calculations. The mod currently requires me to close any UI to open the calculator, and the open/close animation is slow, which makes alt tab much more effective.

**Comment by Rusketh** [comment]
Holding left shift when opening / closing, increases the animation speed by 500%.

**Comment by PowerPotassium** [comment]
Oh that's pretty neat, well that's _half_ of my issue resolved haha

**Comment by Rusketh** [comment]
In the next version you will be able to disable the mouse and keep the calculator open, unfortunately i am unable to add support for the calculator button to work in other GUI's.
