### ISSUE TITLE
Mouse Clicker Stuck - Control GUI Does not work.

### ISSUE THREAD

**Issue by catinabeanbag** [Rusketh/FML_Calculator#7]
The latest update to the mod added the sticky note function to the already useful UI, but also appears to have broken it. Neither me or my friend have been able to do anything with the key binds listed, and it doesn't seem to be working at all. Is this just a multiplayer issue, or is anyone else finding this to be the case?

**Comment by Rusketh** [comment]
Bug confirmed but unable to reproduce locally. Have renamed this thread and will advise users effected to post info here.

**Comment by Rusketh** [comment]
Ok, I have made a tiny little change to the control menu. Included in beta 0.0.8 please test this fix and let me know your results.

Thanks

**Comment by Rusketh** [comment]
OK, i have scrapped the darn control menu entirely. I have also tried to make it smarter, so it wont let your mouse get stuck. Please test with Alpha 0.0.9

Thank you,
this was a good bug report.

Will close once confirmed.
